data_dir: data
torrent_dir: torrents
frequency: 0
entry_limit: 1048576
delete_tiles: true
logs:
- name: geomys_tuscolo2025h2
  log_url: https://tuscolo2025h2.skylight.geomys.org/
  feed_url: http://127.0.0.1/geomys_tuscolo2025h2/feed.xml

# TODO - See's a lot of 403s.
# - name: cloudflare_cftest2025h1a
#   log_url: https://static-ct-public-cftest2025h1a.cloudflareresearch.com/
#   feed_url: http://127.0.0.1/cloudflare_cftest2025h1a/feed.xml
